# Generated by Django 3.2.25 on 2024-05-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icard_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
    ]
